const { PrismaClient } = require("@prisma/client");

async function seed() {
	const prisma = new PrismaClient();

	try {
		// Insert data into the database
		const roleLevel = await prisma.nucleus_role_level.createMany({
			data: [
				// Your data here
				{
					level_name: "Potal_level",
					level_desc: "Potal_level",
					is_active: true,
					created_by: 11,
					modified_by: 11,
					// Add more rows as needed
				},
				{
					level_name: "Entity_level",
					level_desc: "Entity_level",
					is_active: true,
					created_by: 11,
					modified_by: 11,
					// Add more rows as needed
				},
				{
					level_name: "Buisness_level",
					level_desc: "Buisness_level",
					is_active: true,
					created_by: 11,
					modified_by: 11,
					// Add more rows as needed
				},
			],
		});

		const role = await prisma.nucleus_role_main.createMany({
			data: [
				// Your data here
				{
					role_name: "Mega admin",
					level_id: 1,
					role_desc: "Mega admin",
					is_read_allowed: false,
					is_write_allowed: false,
					is_update_allowed: false,
					is_delete_allowed: false,
					is_active: false,
					created_by: 11,
					modified_by: 11,
				},
				{
					role_name: "admin",
					level_id: 2,
					role_desc: "admin",
					is_read_allowed: false,
					is_write_allowed: false,
					is_update_allowed: false,
					is_delete_allowed: false,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					role_name: "super admin",
					level_id: 3,
					role_desc: "super admin",
					is_read_allowed: false,
					is_write_allowed: false,
					is_update_allowed: false,
					is_delete_allowed: false,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					role_name: "legal admin",
					level_id: 1,
					role_desc: "legal admin",
					is_read_allowed: false,
					is_write_allowed: false,
					is_update_allowed: false,
					is_delete_allowed: false,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					role_name: "Director",
					level_id: 2,
					role_desc: "Director",
					is_read_allowed: false,
					is_write_allowed: false,
					is_update_allowed: false,
					is_delete_allowed: false,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					role_name: "Dept.Manager",
					level_id: 3,
					role_desc: "Dept.Manager",
					is_read_allowed: false,
					is_write_allowed: false,
					is_update_allowed: false,
					is_delete_allowed: false,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},

				{
					role_name: "Dept.User",
					level_id: 1,
					role_desc: "Dept.User",
					is_read_allowed: false,
					is_write_allowed: false,
					is_update_allowed: false,
					is_delete_allowed: false,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
			],
		});

		const org = await prisma.nucleus_organization_main.createMany({
			data: [
				{
					id: 1,
					organization_name: "ait global",
					org_image: "xyz",
					domain: null,
					website: "xyz.com",
					total_employees: "250",
					registration_number: "acnp",
					org_start_date: "2023-11-07T00:00:00.000Z",
					phone_number: "9546135933",
					secondary_phone: null,
					email: "abc@gmail.com",
					secondary_email: null,
					fax_number: null,
					country: "india",
					state: "MH",
					city: "pune",
					address: "viman nagar",
					description: "xyz",
					org_head: "xyz",
					created_by: 11,
					modified_by: 11,
				},
			],
		});

		const module = await prisma.nucleus_module_main.createMany({
			data: [
				{
					organization_id: 1,
					module_name: "NIRA Nanotrack",
					module_desc:
						"Monitor, track, and manage attendance and timesheets with extreme precision",
					is_active: false,
					is_enabled: false,
					is_ai_enabled: false,
					module_title: "Time & Attendance ",
					created_by: 11,
					modified_by: 11,
				},
				{
					organization_id: 1,
					module_name: "Nira NEO",
					module_desc: "Strategize, plan, and act with data-driven insights",
					is_active: false,
					is_enabled: false,
					is_ai_enabled: false,
					module_title: "Analytics",
					created_by: 11,
					modified_by: 11,
				},
				{
					organization_id: 1,
					module_name: "Nira Nucleon",
					module_desc:
						"Simplify core HR tasks with solutions that free you from administrative work",
					is_active: false,
					is_enabled: true,
					is_ai_enabled: false,
					module_title: "Core",
					created_by: 11,
					modified_by: 11,
				},
				{
					organization_id: 1,
					module_name: "Nira Nexellence",
					module_desc:
						"Performance management that transforms potential into actionable excellence",
					is_active: false,
					is_enabled: false,
					is_ai_enabled: false,
					module_title: "PMS",
					created_by: 11,
					modified_by: 11,
				},
				{
					organization_id: 1,
					module_name: "Nira Nexus",
					module_desc: "Boost productivity with intuitive employee self service",
					is_active: false,
					is_enabled: false,
					is_ai_enabled: false,
					module_title: "ESS",
					created_by: 11,
					modified_by: 11,
				},
				{
					organization_id: 1,
					module_name: "Nira Nova",
					module_desc: "Embrace a seamless hiring journey that brings the right talent",
					is_active: false,
					is_enabled: false,
					is_ai_enabled: false,
					module_title: "TA",
					created_by: 11,
					modified_by: 11,
				},
			],
		});

		const site = await prisma.nucleus_sitepreference_main.createMany({
			data: [
				{
					id: 1,
					emp_code: "AIT786",
					date_format_id: "2023-02-02",
					time_format_id: "07:30:10 PM",
					time_zone_id: "('INDIA','05:30:00')",
					currency_id: "Rupay",
					password_id: "Hamid@123",
					description: null,
					font_size: "medium",
					font_type: "Inter",
					colour_primary: "#FFFFFF",
					colour_secondary: "#2292EA33",
					colour_tertiary: "#2292EA",
					login_image: null,
					login_message: null,
					created_by: null,
					modified_by: null,
					is_active: null,
					org_modules: 1,
					employment_status: [],
					country: null,
					state: null,
					city: null,
					org_id: 1,
				},
			],
		});

		const shift = await prisma.nucleus_shift_main.createMany({
			data: [
				{
					name: "Shift 4",
					from: "12:00 PM",
					to: "09:00 PM",
					reason: null,
					is_deleted: false,
					financial_year: "2023-2024",
					created_by: 11,
					modified_by: 11,
				},
				{
					name: "Shift 3",
					from: "08:00 AM",
					to: "05:00 PM",
					reason: null,
					is_deleted: false,
					financial_year: "2023-2024",
					created_by: 11,
					modified_by: 11,
				},
				{
					name: "Shift 2",
					from: "11:00 AM",
					to: "08:00 PM",
					reason: null,
					is_deleted: false,
					financial_year: "2023-2024",
					created_by: 11,
					modified_by: 11,
				},
				{
					name: "Shift 1",
					from: "01:00 PM",
					to: "10:00 PM",
					reason: null,
					is_deleted: false,
					financial_year: "2023-2024",
					created_by: 11,
					modified_by: 11,
				},
			],
		});

		const designation = await prisma.nova_designation_main.createMany({
			data: [
				{
					id: 1,
					name: "None",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 2,
					name: "Account Manager",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 3,
					name: "Administrator",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 4,
					name: "Android Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 5,
					name: "Application Support Associate",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 6,
					name: "Application Support Engineer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 7,
					name: "Assistant Team Manager",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 8,
					name: "Associate Engineer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 9,
					name: "Associate Recruiter - US Staffing",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 10,
					name: "Associate Software Engineer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 11,
					name: "Automation Test Engineer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 12,
					name: "AWS Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 13,
					name: "BDE",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 14,
					name: "Business Analyst",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 15,
					name: "CEO",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 16,
					name: "Cloud Lead",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 17,
					name: "Cold Fusion Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 18,
					name: "Consultant",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 19,
					name: "Content Writer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 20,
					name: "Database Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 21,
					name: "Delivery Head",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 22,
					name: "Delivery Head - US Staffing",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 23,
					name: "Director",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 24,
					name: "Dotnet Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 25,
					name: "Edgar Associate",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 26,
					name: "Finance and Account Manager",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 27,
					name: "Financial Analyst",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 28,
					name: "Full Stack Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 29,
					name: "Global Delivery Head",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 30,
					name: "HR Associate",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 31,
					name: "HR Consultant",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 32,
					name: "HR Executive",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 33,
					name: "HR Manager",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 34,
					name: "HR-Operation",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 35,
					name: "Intern",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 36,
					name: "Java Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 37,
					name: "Jr. Full Stack Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 38,
					name: "Jr. QA Engineer Automation",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 39,
					name: "Jr.Designer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 40,
					name: "Lead HR",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 41,
					name: "Lead HR Executive",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 42,
					name: "Lead Software Engineer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 43,
					name: "Network Engineer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},

				{
					id: 44,
					name: "Node.js Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 45,
					name: "Office Admin",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 46,
					name: "Project Manager",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 47,
					name: "Python Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 48,
					name: "QA Engineer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 49,
					name: "QA Manager",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 50,
					name: "QA Test Engineer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 51,
					name: "Quality Specialist",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 52,
					name: "Sales Consultant",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},

				{
					id: 53,
					name: "Scrum Master",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 54,
					name: "Shift Lead",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 55,
					name: "Software Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 56,
					name: "Software Engineer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 57,
					name: "Software Engineer - Trainee",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 58,
					name: "Software Engineer QA",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 59,
					name: "Solution Architect",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 60,
					name: "Sr. Application Support Associate",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 61,
					name: "Sr. AWS DevOps Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 62,
					name: "Sr. Database Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 63,
					name: "Sr. Dot Net Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 64,
					name: "Sr. Full Stack Lead Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 65,
					name: "Sr. Java Architect",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 66,
					name: "Sr. QA Engineer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 67,
					name: "Sr. QA Lead Associate",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 68,
					name: "Sr. Software Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 69,
					name: "Sr. Software Engineer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 70,
					name: "Sr. System Administrator",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 71,
					name: "Sr. Technical Support Engineer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 72,
					name: "Sr. UI/UX Designer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 73,
					name: "Sr.Automation Engineer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 74,
					name: "Sr.DevOps Engineer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 75,
					name: "Sr.Full Stack Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 76,
					name: "Sr.Java Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 77,
					name: "Sr.QA Associate",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 78,
					name: "Sr.Technical Recruiter - US staffing",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 79,
					name: "Sr.UI Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 80,
					name: "System Administrator",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 81,
					name: "Team Lead",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 82,
					name: "Team Lead - US Staffing",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 83,
					name: "Technical Delivery Manager",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 84,
					name: "Technical Lead",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 85,
					name: "Technical Recruiter - US Staffing",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 86,
					name: "Technical Support Analyst",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 87,
					name: "Technical Support Associate",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 88,
					name: "Test Team Manager",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 89,
					name: "UI Designer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 90,
					name: "UI Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 91,
					name: "Vice President",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 92,
					name: "Web Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
			],
		});

		const qualification = await prisma.nova_highest_qualification_main.createMany({
			data: [
				{
					id: 1,
					name: "None",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 2,
					name: "Advanced Diploma",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 3,
					name: "B.A",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 4,
					name: "B.Arch",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 5,
					name: "B.Com",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 6,
					name: "B.E.",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 7,
					name: "B.Ed",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 8,
					name: "B.F.A",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 9,
					name: "B.L",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 10,
					name: "B.SC.",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 11,
					name: "B.Tech",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 12,
					name: "BBA",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 13,
					name: "BBM",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 14,
					name: "BBS",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 15,
					name: "BCA",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 16,
					name: "BJMC",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 17,
					name: "BSW",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 18,
					name: "CA",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 19,
					name: "CFA",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 20,
					name: "CS",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 21,
					name: "Currently Pursuing Graduation",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 22,
					name: "Diploma",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 23,
					name: "M.A",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 24,
					name: "M.C.A.",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 25,
					name: "M.Ed",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 26,
					name: "M.S.",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 27,
					name: "M.Sc.",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 28,
					name: "M.Tech",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 29,
					name: "MBA",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 30,
					name: "MBM",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 31,
					name: "ME",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 32,
					name: "MSW",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 33,
					name: "Others",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 34,
					name: "PG Diploma",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 35,
					name: "PhD",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
			],
		});

		const jobtype = await prisma.nova_job_type_main.createMany({
			data: [
				{
					id: 1,
					name: "None",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 2,
					name: "Permanent",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 3,
					name: "Temporary",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 4,
					name: "Contract To Hire",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 5,
					name: "Full time",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 6,
					name: " Any",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 7,
					name: "Part time",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 8,
					name: "Contract",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 9,
					name: "Training",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 10,
					name: "Volunteer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 11,
					name: "Seasonal",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 12,
					name: "Freelance",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
			],
		});

		const source = await prisma.nova_profile_source_main.createMany({
			data: [
				{
					id: 1,
					name: "None",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 2,
					name: "Added by Recruiter",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 3,
					name: "Advertisement",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 4,
					name: "CareerSite",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 5,
					name: "Careersite - Chatbot",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 6,
					name: "Cold Call",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 7,
					name: "Embed",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 8,
					name: "Employee Referral",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 9,
					name: "External Referral",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 10,
					name: "Facebook",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 11,
					name: "Google import",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 12,
					name: "Import",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 13,
					name: "Imported by parser",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 14,
					name: "Imported from Nova CRM",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 15,
					name: "Indeed Resume",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 16,
					name: "Internal",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 17,
					name: "Vendor",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 18,
					name: "Naukri",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 19,
					name: "Resume Inbox",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 20,
					name: "Twitter",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 21,
					name: "Google+",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 22,
					name: "Calendar Booking",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 23,
					name: "Candidate Portal",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
			],
		});

		const salary = await prisma.nova_salary_range_main.createMany({
			data: [
				{
					id: 1,
					name: "None",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 2,
					name: "0-5L",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 3,
					name: "5.1-10L",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 4,
					name: "10.1-15L",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 5,
					name: "15.1-20L",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 6,
					name: "20.1-25L",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 7,
					name: "25L+",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
			],
		});

		const skill = await prisma.nova_skillset_main.createMany({
			data: [
				{
					id: 1,
					name: "None",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 2,
					name: "Full Stack Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 3,
					name: "Java Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 4,
					name: "UI Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 5,
					name: "QA Engineer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 6,
					name: "Python Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 7,
					name: "Java Technical Lead",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 8,
					name: "AWS Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 9,
					name: "Dot Net Developer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
			],
		});

		const reminder = await prisma.nova_reminder_main.createMany({
			data: [
				{
					id: 1,
					name: "None",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 2,
					name: "At time of event",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 3,
					name: "5 minutes before",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 4,
					name: "10 minutes before",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 5,
					name: "15 minutes before",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 6,
					name: "30 minutes before",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 7,
					name: "1 hour before",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 8,
					name: "2 hours before",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 9,
					name: "1 day before",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 10,
					name: "2 days before",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
			],
		});

		const workexp = await prisma.nova_work_experience_main.createMany({
			data: [
				{
					id: 1,
					name: "None",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 2,
					name: "Fresher",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 3,
					name: "0-1 year",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 4,
					name: "0-2 years",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 5,
					name: "1-3 years",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 6,
					name: "2-5 years",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 7,
					name: "2-6 years",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 8,
					name: "3-6 years",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 9,
					name: "4-8 years",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 10,
					name: "5-8 years",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 11,
					name: "6-9 years",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 12,
					name: "7-9 years",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 13,
					name: "8-12 years",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 14,
					name: "9-12 years",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 15,
					name: "12+ years",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
			],
		});

		const candidate_status = await prisma.nucleus_user_status.createMany({
			data: [
				{
					id: 1,
					name: "New",
					category: "Recruiter Screening",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 2,
					name: "Qualified",
					category: "Recruiter Screening",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 3,
					name: "Attempted to Contact",
					category: "Recruiter Screening",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 4,
					name: "Contacted",
					category: "Recruiter Screening",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 5,
					name: "Not Contacted",
					category: "Recruiter Screening",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 6,
					name: "Contact in Future",
					category: "Recruiter Screening",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 7,
					name: "Associated",
					category: "Recruiter Screening",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 8,
					name: "Submitted-to-hiring manager",
					category: "HM Submissions",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 9,
					name: "Approved by hiring manager",
					category: "HM Screening Reviews",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 10,
					name: "On-Hold by hiring manager",
					category: "HM Screening Reviews",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 11,
					name: "Rejected by hiring manager",
					category: "HM Screening Reviews",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 12,
					name: "Interview-Scheduled",
					category: "Interviews",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 13,
					name: "Interview No-Show",
					category: "Interviews",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 14,
					name: "Selected - L1",
					category: "Interviews",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 15,
					name: "On-Hold - L1",
					category: "Interviews",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 16,
					name: "Rejected - L1",
					category: "Interviews",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 17,
					name: "Selected - L2",
					category: "Interviews",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 18,
					name: "On-Hold - L2",
					category: "Interviews",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 19,
					name: "Rejected - L2",
					category: "Interviews",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 20,
					name: "Selected - L3",
					category: "Interviews",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 21,
					name: "On-Hold - L3",
					category: "Interviews",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 22,
					name: "Rejected - L3",
					category: "Interviews",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 23,
					name: "Selected - L4",
					category: "Interviews",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 24,
					name: "On-Hold - L4",
					category: "Interviews",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 25,
					name: "Rejected - L4",
					category: "Interviews",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 26,
					name: "LOI/LOC Sent",
					category: "Offers",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 27,
					name: "To-be-Offered",
					category: "Offers",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 28,
					name: "Offer-Made",
					category: "Offers",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 29,
					name: "Offer-Accepted",
					category: "Offers",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 30,
					name: "Offer-Declined",
					category: "Offers",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 31,
					name: "Offer-Withdrawn",
					category: "Offers",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 32,
					name: "Drop Out",
					category: "Offers",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 33,
					name: "Hired",
					category: "Hired",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 34,
					name: "No-Show On Joining Date",
					category: "Hired",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 35,
					name: "Unqualified",
					category: "Rejected",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 36,
					name: "Junk candidate",
					category: "Rejected",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 37,
					name: "Rejected",
					category: "Rejected",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 38,
					name: "Rejected-Hirable",
					category: "Rejected",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 39,
					name: "HR Reject",
					category: "Rejected",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 40,
					name: "Converted - Temp",
					category: "Others",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 41,
					name: "Converted - Employee",
					category: "Others",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 42,
					name: "Forward-to-Onboarding",
					category: "Others",
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
			],
		});

		const industry = await prisma.nova_industry_main.createMany({
			data: [
				{
					id: 1,
					name: "None",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 2,
					name: "Administration",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 3,
					name: "Advertising",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 4,
					name: "Agriculture",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 5,
					name: "Architecture & Construction",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 6,
					name: "Arts & Graphics",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 7,
					name: "Airline - Aviation",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 8,
					name: "Accounting",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 9,
					name: "Automotive",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 10,
					name: "Banking",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 11,
					name: "Biotechnology",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 12,
					name: "Broadcasting",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 13,
					name: "Business Management",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 14,
					name: "Charity",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 15,
					name: "Catering",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 16,
					name: "Customer Service",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 17,
					name: "Chemicals",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 18,
					name: "Construction",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 19,
					name: "Consulting",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 20,
					name: "Communications",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 21,
					name: "Computer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 22,
					name: "Consumer",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 23,
					name: "Cosmetics",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 24,
					name: "Design",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 25,
					name: "Defence",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 26,
					name: "Education",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 27,
					name: "Electronics",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 28,
					name: "Engineering",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 29,
					name: "Energy and Utilities",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 30,
					name: "Entertainment",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 31,
					name: "Employment - Recruiting - Staffing",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 32,
					name: "Environmental",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 33,
					name: "Exercise - Fitness",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 34,
					name: "Export/Import",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 35,
					name: "Fashion",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 36,
					name: "Financial Services",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 37,
					name: "FMCG/Foods/Beverage",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 38,
					name: "Fertilizers/Pesticides",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 39,
					name: "Furniture",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 40,
					name: "Grocery",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 41,
					name: "Gas",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 42,
					name: "Government",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 43,
					name: "Government & Public Sector",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 44,
					name: "Government/Military",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 45,
					name: "Gems & Jewellery",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 46,
					name: "Health Care",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 47,
					name: "Human Resources",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 48,
					name: "Hospitality",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 49,
					name: "Hotels and Lodging",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 50,
					name: "HVAC",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 51,
					name: "Hardware",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 52,
					name: "Insurance",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 53,
					name: "Installation",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 54,
					name: "Industrial",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 55,
					name: "IT Services",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 56,
					name: "Internet Services",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 57,
					name: "Import - Export",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 58,
					name: "Legal",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 59,
					name: "Logistics",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 60,
					name: "Landscaping",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 61,
					name: "Leisure and Sport",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 62,
					name: "Library Science",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 63,
					name: "Marketing",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 64,
					name: "Management",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 65,
					name: "Manufacturing",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 66,
					name: "Merchandising",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 67,
					name: "Medical",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 68,
					name: "Media",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 69,
					name: "Metals",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 70,
					name: "Mining",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 71,
					name: "Military",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 72,
					name: "Mortgage",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 73,
					name: "Marine",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 74,
					name: "Maritime",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 75,
					name: "Nonprofit Charitable Organizations",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 76,
					name: "NGO/Social Services",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 77,
					name: "Newspaper",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 78,
					name: "Oil & Gas",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 79,
					name: "Other",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 80,
					name: "Other/Not Classified",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 81,
					name: "Polymer / Plastic / Rubber",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 82,
					name: "Pharma",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 83,
					name: "Pharma/Biotech/Clinical Research",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 84,
					name: "Public Sector and Government",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 85,
					name: "Printing/Packaging/Publishing",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 86,
					name: "Personal and Household Services",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 87,
					name: "Property & Real Estate",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 88,
					name: "Paper",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 89,
					name: "Pet Store",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 90,
					name: "Public Relations",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 91,
					name: "Retail",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 92,
					name: "Real Estate",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 93,
					name: "Retail & Wholesale",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 94,
					name: "Recreation",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 95,
					name: "Real Estate and Property",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 96,
					name: "Recruitment/Employment Firm",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 97,
					name: "Real Estate/Property Management",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 98,
					name: "Restaurant/Food Services",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 99,
					name: "Rental Services",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 100,
					name: "Research & Development",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 101,
					name: "Repair / Maintenance Services",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 102,
					name: "Services",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 103,
					name: "Sales - Marketing",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 104,
					name: "Science & Technology",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 105,
					name: "Security/Law Enforcement",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},

				{
					id: 106,
					name: "Shipping/Marine",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 107,
					name: "Security and Surveillance",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 108,
					name: "Sports and Physical Recreation",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 109,
					name: "Staffing/Employment Agencies",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 110,
					name: "Social Services",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 111,
					name: "Sports Leisure & Lifestyle",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 112,
					name: "Semiconductor",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 113,
					name: "Services - Corporate B2B",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 114,
					name: "Technology",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 115,
					name: "Travel",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 116,
					name: "Training",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 117,
					name: "Transportation",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 118,
					name: "Telecommunications",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 119,
					name: "Trade and Services",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 120,
					name: "Travel and Tourism",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 121,
					name: "Textiles/Garments/Accessories",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 122,
					name: "Tyres",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 123,
					name: "Utilities",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 124,
					name: "Wireless",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 125,
					name: "Wood / Fibre / Paper",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 126,
					name: "Waste Management",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 127,
					name: "Wholesale Trade/Import-Export",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
			],
		});

		const employee = await prisma.nucleus_employee_main.createMany({
			data: [
				{
					employee_code: "AIT786",
					salutation: "Mr.",
					first_name: "Hamid",
					last_name: "Obaid",
					date_of_birth: "1998-02-04T00:00:00Z",
					email_address: "hamid.obaid@aitglobalinc.com",
					contact_number: "919546135933",
					password: "$2b$10$3DYrUUvNtZjRB3BOCapdL.GdZhqggwcuSH4h5h.jk3.H.AQoK.DAC",
					reporting_manager_id: "AIT403",
					designation_id: 8,
					employee_type: "Permanent",
					employee_status: "Permanent",
					gender: "Male",
					marital_status: "Single",
					emergency_contact_number: "9546135933",
					relevant_experience: "1 year(s) 1 month(s)",
					role_id: 3,
					profile_image: "",
					total_experience: "1 year(s) 1 month(s)",
					primary_skill: "Python",
					secondary_skill: "Python",
					source_of_hire_id: "1",
					seating_location: "Pune PDC",
					date_of_contract: "2022-11-30T00:00:00Z",
					notice_period: "",
					team_name: "AIT Internal",
					date_of_confirmation: "2022-11-30T00:00:00Z",
					client: "AIT Global India",
					probation_status: "Confirmed",
					probation_extended_date: "2022-11-30T00:00:00Z",
					probation_period: "180",
					probation_due_date: "2022-08-20T00:00:00Z",
					joining_day: "",
					joining_status: "",
					contract_end_date: "2022-08-20T00:00:00Z",
					invalid_attempt: null,
					lock_time: null,
					password_history:
						",$2b$10$3DYrUUvNtZjRB3BOCapdL.GdZhqggwcuSH4h5h.jk3.H.AQoK.DAC",
					employee_full_name: "Md Hamid Obaid",
					employee_ip_address: "",
					background_check_status: "",
					job_title_id: null,
					tour_flag: null,
					mode_of_entry: null,
					entry_comments: null,
					candidate_referred_by: null,
					company_id: null,
					employee_temp_lock: null,
					employee_reason_locked: null,
					employee_locked_date: null,
					google_id: null,
					shift_id: 1,
					date_of_joining: null,
					date_of_leaving: null,
					business_unit_id: null,
					legal_entity_id: null,
					division_id: null,
					department_id: null,
					extension_number: null,
					office_number: null,
					office_fax_number: null,
					is_mega_admin: null,
					is_active: true,
				},
			],
		});

		const team = await prisma.nova_team_main.createMany({
			data: [
				{
					id: 1,
					name: "None",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 2,
					name: "Accounts",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 3,
					name: "Admin",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 4,
					name: "AIT Internal",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 5,
					name: "AWS",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 6,
					name: "Cold Fusion",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 7,
					name: "DevOps Team",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 8,
					name: "Dotnet Team",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 9,
					name: "HR",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
				{
					id: 10,
					name: "Python Team",
					is_deleted: null,
					is_active: true,
					created_by: 11,
					modified_by: 11,
				},
			],
		});
	} finally {
		// Close the Prisma client
		await prisma.$disconnect();
	}
}

seed().catch((error) => {
	console.error(error);
});
